girldevelopit/gdi-new-site

.travis.yml
README.md
build.travis.yml

Adding .yml config and a build graphic.

Adding Travis CI to the site

---

README.md

When I started doing development work on the website I had to do a bit of setup to get everything working.  This is an attempt to document the steps I had to take to get everything working.  Would you please let me know if they're 'good enough' for a rough draft, and any help with wording/formatting/etc would be greatly appreciated.

Adding ubuntu installation instructions

---

app/controllers/application_controller.rb

This PR is a wrapper of the first step of @mathemagica's fine work on #101, which I tested locally with the following muuuch better results:

Redirect Users Without Admin Permissions to Home

---

app/admin/admin_user.rb

Display Admin Roles on Admin User Dashboard

---

app/admin/bio.rb
app/views/chapters/_meetup_map.html.erb
app/views/chapters/show.html.erb

This does the trick, but feel free to nitpick zee logic!

Fixing Meetup API data pull by rearranging _.each statement

---

app/admin/bio.rb
app/admin/sponsor.rb
app/views/chapters/_meetup_map.html.erb
app/views/chapters/show.html.erb

Fixed bio image uploader. Added the fix to the sponsors page as well.
My API fixes are showing in here too...that's okay, right? Let me know otherwise...

Fixing AA upload

---

app/views/home/index.html.erb

Please see the change for context.

Fixing a typo from 'woman' to 'women' on the index page.

---

config/routes.rb

This pull request is a fix for https://github.com/girldevelopit/gdi-new-site/issues/138
As the commit says.

add route to reroute codeofconduct to code-of-conduct

---

config/environments/production.rb

Also using config variables here

Adding Mandrill settings to prod environment

---

config/environments/production.rb

Adding default url in production, too.

Additional tweaks to production mail settings

---

app/assets/stylesheets/typography.css.scss

I adjusted the font size, line weight, and line height to make the
paragraph text a little more visible. In Chrome I had no problem seeing
it, but on Mac the text was a bit hard to read. It should read across
the site for p and p.large.

Issue #123 Font Size

---

app/views/home/index.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_header.html.erb

This simply adds target="_blank" to the external links

add target blank to external links (twitter, facebook, tumbler)

---

spec/models/chapter_spec.rb

Improves test coverage by 1.5%

Add test for chapter helper module #image_route

---

app/views/layouts/application.html.erb

adding english to language attribute of html tag

---

app/assets/stylesheets/typography.css.scss
app/views/home/donate.html.erb

The donate button looked like a generic paypal button and we wanted to look more legit than that.
I made some mad CSS styles to make it GDI friendly
Go to the /donate page and bask in the beauty of a submit button turned flat.
#62
*Here is a pingwing picture for your troubles...*

Styles for the donate button so it's not looking all paypal like.

---

app/views/chapters/show.html.erb

Removing space from meetup link

---

app/assets/stylesheets/layout.css.scss
app/views/layouts/application.html.erb

There was no way for the world to know that you could fork our repo! 
I added the generic white ribbon because we're classy.
Go to any page and see the ribbon! If you are at a screen size that is small enough for the ribbon to overlap the nav, you will NOT see it. I care about usability.
*Here is a pengling picture for your troubles...*

Adding a fork me ribbon to the page. Making it responsive

---

app/views/home/donate.html.erb

Could use some design/layout love.

Adding donations copy

---

app/views/chapters/_social_media_bio.html.erb

https://github.com/girldevelopit/gdi-new-site/issues/198

fix(social media bio): fix linkedin profile links

---

CONTRIBUTORS.md

This pull requests solves both #211 + #212. I did not separate them out into two different pull requests since each issue is a simple change to the same file.

Update CONTRIBUTORS.md, refs #211 + #212.

---

app/views/layouts/_google_analytics.html.erb
app/views/layouts/application.html.erb
config/environments/development.rb
config/environments/production.rb

Using the current/live GDI tracking code for production environment so not sure if we want to merge this yet? The development code (made with new dev account) is tried and tested on my local machine so we're good there. 'Least it's ready when we are! :+1:

Adding google analytics for prod/dev environments

---

app/assets/stylesheets/about.css.scss
app/views/home/about.html.erb

Returning proper spacing to the about page sections. I noticed all the links in @DBNess's bio were empty so I filled them...assuming her name links to her personal site, right?

Fix margins on about and filling empty links, ref #215

---

app/assets/stylesheets/application.css.scss
app/views/chapters/_meetup_map.html.erb
app/views/chapters/show.html.erb

The only links we should worry about are the embedded/imported links, which are changed in this PR. The many other links are either simple links or references in comments thus do not (and shouldn't) be altered.

Changing embedded/imported links to match https, fixes #218

---

app/admin/bio.rb
app/admin/sponsor.rb

Dropdowns are much prettier now :)

Fixes #203 chapter/bio page dropdown bug in Active Admin

---

app/views/shared/_footer.html.erb

Now the footer would link to the new chapter interest form that is linked to on the Chapters page: https://www.girldevelopit.com/chapters

Added Link to New Chapter interest form in Footer

---

app/assets/stylesheets/base.css.scss
app/assets/stylesheets/chapters.css.scss
app/assets/stylesheets/layout.css.scss
app/assets/stylesheets/typography.css.scss

* Link color was too low contrast
* Text size of nav is too small.
* Changed font color fo links
* Increased text-size
Navigate to the site and celebrate its increased readability! 
*Here is a cute animal picture for your troubles...*

Adding link color and increasing font size for nav. Fixes #204 & #242

---

app/assets/stylesheets/layout.css.scss
app/views/layouts/application.html.erb

@Roenok would love to have you take a look at this! Since you don't have a local dev setup, I made this recording of the way to fix works on my local machine. http://g.recordit.co/RBHKF0T1pr.gif
Also, I was not able to take your HTML/CSS literally the way you laid it out. `main-container` is a class name that is spread out among several views. It made more sense to create a an id that lived in `application.html.erb` instead so that the change only effected one template, but still accomplished the task.

Adding skip nav HTML + CSS, refs #210.

---

app/assets/stylesheets/layout.css.scss

resolving #238 where footer doesn't reach bottom of page on mobile

---

app/assets/stylesheets/layout.css.scss
app/views/shared/_footer.html.erb

adding mailchimp to footer, fixes #256

---

app/views/shared/_footer.html.erb

reducing mailchimp field size, fixes #260

---

app/assets/stylesheets/home-page.css.scss
app/assets/stylesheets/layout.css.scss

Screenshot of proposed change:

Fix header navigation overflow on mobile - fixes #239

---

app/views/chapters/show.html.erb

#291 Add a 'More Events' link to chapters/show page when there are events present.

Issue #291: Add 'More Events' link below GDI Chapter events list

---

app/admin/bio.rb
app/admin/material.rb
app/admin/sponsor.rb
app/controllers/chapters_controller.rb
app/controllers/materials_controller.rb
db/migrate/20150310040232_add_sort_to_bios.rb
db/migrate/20150310040249_add_sort_to_sponsors.rb
db/migrate/20150310040256_add_sort_to_materials.rb
db/schema.rb

Adding sort column to bios, materials, and sponsors; Fixes #202, fixes #217
